### ISSUE TITLE
nanoid not found

### ISSUE THREAD

**Issue by jrichardsz** [usil/eventhos-api#12]
if it is installed with npm install nanoid

The start in production mode exists with log.

After deep line by line research, the error is due to nanoid

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /tmp/workspace/eventhos-api/node_modules/nanoid/index.js
require() of ES modules is not supported.
require() of /tmp/workspace/eventhos-api/node_modules/nanoid/index.js from /tmp/workspace/eventhos-api/dist/main.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /tmp/workspace/eventhos-api/node_modules/nanoid/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at /tmp/workspace/eventhos-api/dist/main.js:159:41
    at /tmp/workspace/eventhos-api/dist/main.js:1998:3
    at Object.<anonymous> (/tmp/workspace/eventhos-api/dist/main.js:2000:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by jrichardsz** [comment]
fixed https://github.com/usil/eventhos-api/pull/27
